# Basic provisioning example
- name: Ansible test
  hosts: localhost
  vars:
    ansible_python_interpreter: /bin/python3
  tasks:
    - name: destroy ECR
      ecs_ecr:
        name: super/cool
        state: absent
      register: aws_ecr
