---
- name: ECR repository destroy force
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: destroy ECR forcibly
      shell: |
        aws ecr delete-repository --repository-name {{ name }} --force
