# Basic provisioning example
- name: Ansible test
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: create ECR
      ecs_ecr:
        name: super/cool
        state: present
      register: aws_ecr

    - name: login ECR
      ansible.builtin.script:
        cmd:  ecr-login.sh {{ aws_ecr.repository.repositoryUri }}
