---
- name: ECR repository destroy 
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: destroy ECR
      ecs_ecr:
        name: "{{ name }}"
        state: absent
      register: aws_ecr