# Basic provisioning example
- name: Ansible test
  hosts: localhost
  tasks:
    - name: create VPC
      ec2_vpc_net:
        name: Test VPC
        cidr_block: 10.1.0.0/16
        region: ap-northeast-2
        state: present
      register: vpc_result
      vars:
        ansible_python_interpreter: /bin/python3
